# Generated by Django 2.2.4 on 2020-06-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('no_subjects', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('course_type', models.PositiveSmallIntegerField(choices=[(1, 'BCA'), (2, 'MCA'), (3, 'MBA')])),
            ],
        ),
    ]
